---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "devportal"
  namespace: "iwhi-infra"
  labels:
    app: "devportal"
spec:
  selector:
    matchLabels:
      app: "devportal" 
  template: 
    metadata:
      labels:
        app: "devportal"
    spec:
      containers:
        - name: "devportal"
          image: "cp.icr.io/cp/webmethods/api/ibm-webmethods-developer-portal:11.1"
          ports:
            - containerPort: 8083
              name: "public-port"
          env:
            - name: "SPRING_ELASTICSEARCH_URIS"
              value: "http://elastic:9200"
      imagePullSecrets:
        - name: regcred
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: "devportal"
  namespace: "iwhi-infra"
spec: 
  ports:
    - name: devportal-ui
      port: 8080
      targetPort: "public-port"
  selector:
    app: "devportal"
  type: LoadBalancer
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dev-portal-ui
  namespace: iwhi-infra
spec:
  host: dev-portal.apps.homelab.servers
  path: /
  to:
    kind: Service
    name: devportal
  port:
    targetPort: devportal-ui
  wildcardPolicy: None