---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "devportal"
  namespace: "iwhi-infra"
  labels:
    app: "devportal"
spec:
  selector:
    matchLabels:
      app: "devportal" 
  template: 
    metadata:
      labels:
        app: "devportal"
    spec:
      containers:
        - name: "devportal"
          image: "cp.icr.io/cp/webmethods/api/ibm-webmethods-developer-portal:11.1"
          ports:
            - containerPort: 8080
              name: "public-http"
            - containerPort: 8083
              name: "public-https"
          env:
            - name: "SPRING_ELASTICSEARCH_URIS"
              value: "http://elastic:9200"
      imagePullSecrets:
        - name: regcred
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: "devportal"
  namespace: "iwhi-infra"
spec: 
  ports:
    - name: devportal-ui
      port: 80
      targetPort: "public-http"
    - name: devportal-ui-https
      port: 443
      targetPort: "public-https"
  selector:
    app: "devportal"
  type: LoadBalancer