---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "universal-messaging"
  namespace: "iwhi-infra"
  labels:
    app: "universal-messaging"
spec:
  selector:
    matchLabels:
      app: "universal-messaging" 
  template: 
    metadata:
      labels:
        app: "universal-messaging"
    spec:
      containers:
        - name: "universal-messaging"
          image: "cp.icr.io/cp/webmethods/universalmessaging/universalmessaging-server"
          ports:
            - containerPort: 9000
              name: "realm-port"
      imagePullSecrets:
        - name: regcred
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: "um"
  namespace: "iwhi-infra"
spec: 
  ports:
    - name: um-realm
      port: 9000
      targetPort: "realm-port"
  selector:
    app: "universal-messaging"
  type: LoadBalancer