---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "universal-messaging"
  namespace: "swag-infra"
  labels:
    app: "universal-messaging"
spec:
  selector:
    matchLabels:
      app: "universal-messaging" 
  template: 
    metadata:
      labels:
        app: "universal-messaging"
    spec:
      containers:
        - name: "universal-messaging"
          image: "sagcr.azurecr.io/universalmessaging-server:10.15"
          ports:
            - containerPort: 9000
              name: "realm-port"
          volumeMounts:
            - name: license-volume
              mountPath: /opt/softwareag/UniversalMessaging/server/umserver/licence/licence.xml
              subPath: licence.xml
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: license-volume
          configMap:
            name: "umlicense"
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: "um"
  namespace: "swag-infra"
spec: 
  ports:
    - name: um-realm
      port: 9000
      targetPort: "realm-port"
  selector:
    app: "universal-messaging"
  type: LoadBalancer